chars = {
        "drawchara": [f"movb 2+&", 
                        f"outb", 
                        f"movb 34+&", 
                        f"outb"
                        ,f"movb 66+&"
                        ,f"outb"
                        ,f"movb 67+&"
                        ,f"outb"
                        ,f"movb 68+&"
                        ,f"outb"
                        ,f"movb 98+&"
                        ,f"outb"
                        ,f"movb 3+&"
                        ,f"outb"
                        ,f"movb 4+&"
                        ,f"outb"
                        ,f"movb 5+&"
                        ,f"outb"
                        ,f"movb 37+&"
                        ,f"outb"
                        ,f"movb 69+&"
                        ,f"outb"
                        ,f"movb 101+&"
                        ,f"outb"],

        "drawcharb": [f"movb 3+&",
                        f"outb", 
                        f"movb 36+&",
                        f"outb",
                        f"movb 67+&",
                        f"outb", 
                        f"movb 100+&",
                        f"outb", 
                        f"movb 131+&",
                        f"outb", 
                        f"movb 34+&", 
                        f"outb", 
                        f"movb 66+&", 
                        f"outb", 
                        f"movb 98+&", 
                        f"outb"],

        "drawcharc": [f"movb 2+&",
                        f"outb",
                        f"movb 34+&",
                        f"outb",
                        f"movb 66+&",
                        f"outb",
                        f"movb 98+&",
                        f"outb",
                        f"movb 99+&",
                        f"outb",
                        f"movb 100+&",
                        f"outb",
                        f"movb 3+&",
                        f"outb",
                        f"movb 4+&",
                        f"outb"],
                        
    "drawchard": [f"movb 2+&",
                        f"outb",
                        f"movb 3+&",
                        f"outb",
                        f"movb 4+&",
                        f"outb",
                        f"movb 37+&",
                        f"outb",
                        f"movb 69+&",
                        f"outb",
                        f"movb 100+&",
                        f"outb",
                        f"movb 34+&",
                        f"outb",
                        f"movb 66+&",
                        f"outb",
                        f"movb 66+&",
                        f"outb",
                        f"movb 99+&",
                        f"outb",
                        f"movb 98+&",
                        f"outb",],

        "drawchare": [f"movb 2+&",
                        f"outb",
                        f"movb 3+&",
                        f"outb",
                        f"movb 4+&",
                        f"outb",
                        f"movb 34+&",
                        f"outb",
                        f"movb 66+&",
                        f"outb",
                        f"movb 67+&",
                        f"outb",
                        f"movb 98+&",
                        f"outb",
                        f"movb 130+&",
                        f"outb",
                        f"movb 131+&",
                        f"outb",
                        f"movb 132+&",
                        f"outb",],

        "drawcharf": [f"movb 2+&",
                        f"outb",
                        f"movb 3+&",
                        f"outb",
                        f"movb 4+&",
                        f"outb",
                        f"movb 34+&",
                        f"outb",
                        f"movb 66+&",
                        f"outb",
                        f"movb 67+&",
                        f"outb",
                        f"movb 98+&",
                        f"outb",
                        f"movb 130+&",
                        f"outb",],

        "drawcharg": [f"movb 2+&",
                        f"outb",
                        f"movb 34+&",
                        f"outb",
                        f"movb 66+&",
                        f"outb",
                        f"movb 98+&",
                        f"outb",
                        f"movb 131+&",
                        f"outb",
                        f"movb 132+&",
                        f"outb",
                        f"movb 101+&",
                        f"outb",
                        f"movb 68+&",
                        f"outb",
                        f"movb 3+&",
                        f"outb",
                        f"movb 4+&",
                        f"outb",],

        "drawcharh": [f"movb 2+&",
                        f"outb",
                        f"movb 34+&",
                        f"outb",
                        f"movb 66+&",
                        f"outb",
                        f"movb 67+&",
                        f"outb",
                        f"movb 68+&",
                        f"outb",
                        f"movb 100+&",
                        f"outb",
                        f"movb 98+&",
                        f"outb",],

        "drawchari": [f"movb 3+&",
                        f"outb",
                        f"movb 2+&",
                        f"outb",
                        f"movb 4+&",
                        f"outb",
                        f"movb 35+&",
                        f"outb",
                        f"movb 67+&",
                        f"outb",
                        f"movb 99+&",
                        f"outb",
                        f"movb 100+&",
                        f"outb",
                        f"movb 98+&",
                        f"outb",],
                    
        "drawcharj": [f"movb 3+&",
                        f"outb",
                        f"movb 35+&",
                        f"outb",
                        f"movb 67+&",
                        f"outb",
                        f"movb 99+&",
                        f"outb",
                        f"movb 100+&",
                        f"outb",
                        f"movb 69+&",
                        f"outb",],

        "drawchark": [f"movb 3+&",
                        f"outb",
                        f"movb 35+&",
                        f"outb",
                        f"movb 36+&",
                        f"outb",
                        f"movb 69+&",
                        f"outb",
                        f"movb 101+&",
                        f"outb",
                        f"movb 5+&",
                        f"outb",
                        f"movb 67+&",
                        f"outb",
                        f"movb 99+&",
                        f"outb",],

        "drawcharl": [f"movb 3+&",
                        f"outb",
                        f"movb 35+&",
                        f"outb",
                        f"movb 67+&",
                        f"outb",
                        f"movb 99+&",
                        f"outb",
                        f"movb 100+&",
                        f"outb",],

        "drawcharm": [f"movb 3+&",
                        f"outb",
                        f"movb 4+&",
                        f"outb",
                        f"movb 37+&",
                        f"outb",
                        f"movb 6+&",
                        f"outb",
                        f"movb 7+&",
                        f"outb",
                        f"movb 39+&",
                        f"outb",
                        f"movb 71+&",
                        f"outb",
                        f"movb 103+&",
                        f"outb",
                        f"movb 35+&",
                        f"outb",
                        f"movb 67+&",
                        f"outb",
                        f"movb 99+&",
                        f"outb",],

        "drawcharn": [f"movb 3+&",
                        f"outb",
                        f"movb 4+&",
                        f"outb",
                        f"movb 37+&",
                        f"outb",
                        f"movb 69+&",
                        f"outb",
                        f"movb 101+&",
                        f"outb",
                        f"movb 35+&",
                        f"outb",
                        f"movb 67+&",
                        f"outb",
                        f"movb 99+&",
                        f"outb",],
}

def add_all_chars_to_macro_definitions(macros):
    for key, value in chars.items():
        macros[key] = value

    return macros